---
## Zabbix agent package / repo
zabbix_agent_ver: "7.4"
zabbix_agent_release_channel: "release"

## Connection
zabbix_agent_server_addr: null
zabbix_agent_server_port: 10051
zabbix_agent_listen_ip: "auto"

## Identity and metadata
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_metadata: "autoregister os=linux"

## TLS (PSK)
zabbix_agent_enable_tls: false
zabbix_agent_tls_psk_identity: ""
zabbix_agent_tls_psk: ""
zabbix_agent_tls_psk_file: "/etc/zabbix/zabbix_agent.psk"

## Logging
zabbix_agent_logfile: "/var/log/zabbix/zabbix_agent2.log"
zabbix_agent_debug_level: 3
zabbix_agent_logfile_size: 0
